// 100 Australian grocery products with AUD prices.
// Prices are indicative of typical Australian supermarket shelf prices.
const PRODUCTS = [
  // Fruit & Veg (15)
  { id: 1,  name: "Cavendish Bananas 1kg",              category: "Fruit & Veg",     price: 4.50,  unit: "per kg",    emoji: "🍌" },
  { id: 2,  name: "Pink Lady Apples 1kg",               category: "Fruit & Veg",     price: 5.90,  unit: "per kg",    emoji: "🍎" },
  { id: 3,  name: "Strawberries 250g Punnet",           category: "Fruit & Veg",     price: 3.50,  unit: "each",      emoji: "🍓" },
  { id: 4,  name: "Hass Avocados",                      category: "Fruit & Veg",     price: 2.20,  unit: "each",      emoji: "🥑" },
  { id: 5,  name: "Truss Tomatoes 1kg",                 category: "Fruit & Veg",     price: 6.90,  unit: "per kg",    emoji: "🍅" },
  { id: 6,  name: "Carrots 1kg Bag",                    category: "Fruit & Veg",     price: 2.00,  unit: "each",      emoji: "🥕" },
  { id: 7,  name: "Brushed Potatoes 2kg",               category: "Fruit & Veg",     price: 4.50,  unit: "each",      emoji: "🥔" },
  { id: 8,  name: "Brown Onions 1kg",                   category: "Fruit & Veg",     price: 2.50,  unit: "each",      emoji: "🧅" },
  { id: 9,  name: "Broccoli",                           category: "Fruit & Veg",     price: 4.90,  unit: "per kg",    emoji: "🥦" },
  { id: 10, name: "Iceberg Lettuce",                    category: "Fruit & Veg",     price: 3.20,  unit: "each",      emoji: "🥬" },
  { id: 11, name: "Lebanese Cucumbers 500g",            category: "Fruit & Veg",     price: 3.90,  unit: "each",      emoji: "🥒" },
  { id: 12, name: "Red Capsicum",                       category: "Fruit & Veg",     price: 8.90,  unit: "per kg",    emoji: "🫑" },
  { id: 13, name: "Navel Oranges 3kg Bag",              category: "Fruit & Veg",     price: 6.90,  unit: "each",      emoji: "🍊" },
  { id: 14, name: "Seedless Watermelon",                category: "Fruit & Veg",     price: 2.90,  unit: "per kg",    emoji: "🍉" },
  { id: 15, name: "Mushroom Cups 500g",                 category: "Fruit & Veg",     price: 6.50,  unit: "each",      emoji: "🍄" },

  // Bakery (10)
  { id: 16, name: "Wholemeal Sandwich Loaf 700g",       category: "Bakery",          price: 3.80,  unit: "each",      emoji: "🍞" },
  { id: 17, name: "White Toast Bread 650g",             category: "Bakery",          price: 2.90,  unit: "each",      emoji: "🍞" },
  { id: 18, name: "Sourdough Vienna 450g",              category: "Bakery",          price: 5.50,  unit: "each",      emoji: "🥖" },
  { id: 19, name: "Hamburger Buns 6 Pack",              category: "Bakery",          price: 4.00,  unit: "each",      emoji: "🍔" },
  { id: 20, name: "Croissants 4 Pack",                  category: "Bakery",          price: 6.00,  unit: "each",      emoji: "🥐" },
  { id: 21, name: "English Muffins 6 Pack",             category: "Bakery",          price: 3.50,  unit: "each",      emoji: "🧁" },
  { id: 22, name: "Hot Cross Buns 6 Pack",              category: "Bakery",          price: 5.00,  unit: "each",      emoji: "🥯" },
  { id: 23, name: "Wraps Wholegrain 8 Pack",            category: "Bakery",          price: 4.50,  unit: "each",      emoji: "🌯" },
  { id: 24, name: "Crumpets 6 Pack",                    category: "Bakery",          price: 3.20,  unit: "each",      emoji: "🥞" },
  { id: 25, name: "Banana Bread Loaf 550g",             category: "Bakery",          price: 7.00,  unit: "each",      emoji: "🍌" },

  // Dairy & Eggs (12)
  { id: 26, name: "Full Cream Milk 2L",                 category: "Dairy & Eggs",    price: 3.10,  unit: "each",      emoji: "🥛" },
  { id: 27, name: "Lite Milk 2L",                       category: "Dairy & Eggs",    price: 3.10,  unit: "each",      emoji: "🥛" },
  { id: 28, name: "Free Range Eggs 12 Pack (700g)",     category: "Dairy & Eggs",    price: 6.50,  unit: "each",      emoji: "🥚" },
  { id: 29, name: "Tasty Cheese Block 500g",            category: "Dairy & Eggs",    price: 8.50,  unit: "each",      emoji: "🧀" },
  { id: 30, name: "Shredded Mozzarella 400g",           category: "Dairy & Eggs",    price: 7.00,  unit: "each",      emoji: "🧀" },
  { id: 31, name: "Greek Yoghurt 1kg",                  category: "Dairy & Eggs",    price: 6.90,  unit: "each",      emoji: "🍦" },
  { id: 32, name: "Salted Butter 500g",                 category: "Dairy & Eggs",    price: 7.50,  unit: "each",      emoji: "🧈" },
  { id: 33, name: "Thickened Cream 300ml",              category: "Dairy & Eggs",    price: 2.80,  unit: "each",      emoji: "🥛" },
  { id: 34, name: "Vanilla Custard 1L",                 category: "Dairy & Eggs",    price: 4.20,  unit: "each",      emoji: "🍮" },
  { id: 35, name: "Cream Cheese 250g",                  category: "Dairy & Eggs",    price: 4.50,  unit: "each",      emoji: "🧀" },
  { id: 36, name: "Oat Milk Barista 1L",                category: "Dairy & Eggs",    price: 3.50,  unit: "each",      emoji: "🌾" },
  { id: 37, name: "Feta Danish Style 200g",             category: "Dairy & Eggs",    price: 5.00,  unit: "each",      emoji: "🧀" },

  // Meat & Seafood (12)
  { id: 38, name: "Chicken Breast Fillets",             category: "Meat & Seafood",  price: 12.50, unit: "per kg",    emoji: "🍗" },
  { id: 39, name: "Chicken Thigh Fillets",              category: "Meat & Seafood",  price: 13.50, unit: "per kg",    emoji: "🍗" },
  { id: 40, name: "Beef Mince Regular",                 category: "Meat & Seafood",  price: 12.00, unit: "per kg",    emoji: "🥩" },
  { id: 41, name: "Beef Scotch Fillet Steak",           category: "Meat & Seafood",  price: 42.00, unit: "per kg",    emoji: "🥩" },
  { id: 42, name: "Lamb Loin Chops",                    category: "Meat & Seafood",  price: 32.00, unit: "per kg",    emoji: "🍖" },
  { id: 43, name: "Pork Sausages 8 Pack",               category: "Meat & Seafood",  price: 7.50,  unit: "each",      emoji: "🌭" },
  { id: 44, name: "Middle Bacon 250g",                  category: "Meat & Seafood",  price: 6.50,  unit: "each",      emoji: "🥓" },
  { id: 45, name: "Sliced Leg Ham 200g",                category: "Meat & Seafood",  price: 5.50,  unit: "each",      emoji: "🍖" },
  { id: 46, name: "Tasmanian Salmon Fillets 2pk",       category: "Meat & Seafood",  price: 14.00, unit: "each",      emoji: "🐟" },
  { id: 47, name: "Barramundi Fillets 400g",            category: "Meat & Seafood",  price: 13.00, unit: "each",      emoji: "🐟" },
  { id: 48, name: "Cooked Tiger Prawns",                category: "Meat & Seafood",  price: 26.00, unit: "per kg",    emoji: "🦐" },
  { id: 49, name: "BBQ Roast Chicken",                  category: "Meat & Seafood",  price: 12.00, unit: "each",      emoji: "🍗" },

  // Pantry (16)
  { id: 50, name: "Jasmine Rice 5kg",                   category: "Pantry",          price: 14.00, unit: "each",      emoji: "🍚" },
  { id: 51, name: "Spaghetti 500g",                     category: "Pantry",          price: 1.60,  unit: "each",      emoji: "🍝" },
  { id: 52, name: "Penne Pasta 500g",                   category: "Pantry",          price: 1.60,  unit: "each",      emoji: "🍝" },
  { id: 53, name: "Pasta Sauce Tomato & Basil 500g",    category: "Pantry",          price: 3.20,  unit: "each",      emoji: "🍅" },
  { id: 54, name: "Rolled Oats 900g",                   category: "Pantry",          price: 3.00,  unit: "each",      emoji: "🌾" },
  { id: 55, name: "Weet-Bix 1.2kg",                     category: "Pantry",          price: 6.50,  unit: "each",      emoji: "🥣" },
  { id: 56, name: "Vegemite 380g",                      category: "Pantry",          price: 6.70,  unit: "each",      emoji: "🥪" },
  { id: 57, name: "Peanut Butter Crunchy 500g",         category: "Pantry",          price: 5.50,  unit: "each",      emoji: "🥜" },
  { id: 58, name: "Strawberry Jam 500g",                category: "Pantry",          price: 4.20,  unit: "each",      emoji: "🍓" },
  { id: 59, name: "Raw Honey Squeeze 500g",             category: "Pantry",          price: 8.00,  unit: "each",      emoji: "🍯" },
  { id: 60, name: "Extra Virgin Olive Oil 1L",          category: "Pantry",          price: 15.00, unit: "each",      emoji: "🫒" },
  { id: 61, name: "Self-Raising Flour 1kg",             category: "Pantry",          price: 2.20,  unit: "each",      emoji: "🌾" },
  { id: 62, name: "Caster Sugar 1kg",                   category: "Pantry",          price: 2.40,  unit: "each",      emoji: "🍬" },
  { id: 63, name: "Tuna in Springwater 425g",           category: "Pantry",          price: 5.00,  unit: "each",      emoji: "🐟" },
  { id: 64, name: "Diced Tomatoes Can 400g",            category: "Pantry",          price: 1.40,  unit: "each",      emoji: "🥫" },
  { id: 65, name: "Baked Beans 555g",                   category: "Pantry",          price: 3.00,  unit: "each",      emoji: "🫘" },

  // Frozen (8)
  { id: 66, name: "Frozen Mixed Vegetables 1kg",        category: "Frozen",          price: 4.00,  unit: "each",      emoji: "🥶" },
  { id: 67, name: "Frozen Peas 500g",                   category: "Frozen",          price: 2.50,  unit: "each",      emoji: "🟢" },
  { id: 68, name: "Potato Chips Straight Cut 1kg",      category: "Frozen",          price: 4.50,  unit: "each",      emoji: "🍟" },
  { id: 69, name: "Fish Fingers 15 Pack",               category: "Frozen",          price: 5.50,  unit: "each",      emoji: "🐟" },
  { id: 70, name: "Margherita Pizza 500g",              category: "Frozen",          price: 6.00,  unit: "each",      emoji: "🍕" },
  { id: 71, name: "Vanilla Ice Cream 2L",               category: "Frozen",          price: 7.00,  unit: "each",      emoji: "🍨" },
  { id: 72, name: "Frozen Blueberries 500g",            category: "Frozen",          price: 8.00,  unit: "each",      emoji: "🫐" },
  { id: 73, name: "Garlic Bread Twin Pack",             category: "Frozen",          price: 4.50,  unit: "each",      emoji: "🥖" },

  // Drinks (10)
  { id: 74, name: "Orange Juice No Pulp 2L",            category: "Drinks",          price: 6.00,  unit: "each",      emoji: "🧃" },
  { id: 75, name: "Sparkling Mineral Water 1.25L",      category: "Drinks",          price: 1.50,  unit: "each",      emoji: "💧" },
  { id: 76, name: "Cola Soft Drink 1.25L",              category: "Drinks",          price: 3.50,  unit: "each",      emoji: "🥤" },
  { id: 77, name: "Lemonade 1.25L",                     category: "Drinks",          price: 3.30,  unit: "each",      emoji: "🍋" },
  { id: 78, name: "Instant Coffee 200g",                category: "Drinks",          price: 12.00, unit: "each",      emoji: "☕" },
  { id: 79, name: "Ground Coffee Beans 1kg",            category: "Drinks",          price: 24.00, unit: "each",      emoji: "☕" },
  { id: 80, name: "English Breakfast Tea 100 Bags",     category: "Drinks",          price: 6.50,  unit: "each",      emoji: "🍵" },
  { id: 81, name: "Iced Coffee Flavoured Milk 750ml",   category: "Drinks",          price: 4.20,  unit: "each",      emoji: "🥤" },
  { id: 82, name: "Kombucha Ginger 330ml",              category: "Drinks",          price: 4.00,  unit: "each",      emoji: "🫧" },
  { id: 83, name: "Sports Drink Blue 600ml",            category: "Drinks",          price: 3.80,  unit: "each",      emoji: "🥤" },

  // Snacks (9)
  { id: 84, name: "Tim Tams Original 200g",             category: "Snacks",          price: 4.50,  unit: "each",      emoji: "🍫" },
  { id: 85, name: "Potato Chips Original 175g",         category: "Snacks",          price: 4.00,  unit: "each",      emoji: "🥔" },
  { id: 86, name: "Corn Chips 230g",                    category: "Snacks",          price: 4.20,  unit: "each",      emoji: "🌽" },
  { id: 87, name: "Milk Chocolate Block 180g",          category: "Snacks",          price: 6.00,  unit: "each",      emoji: "🍫" },
  { id: 88, name: "Muesli Bars 6 Pack",                 category: "Snacks",          price: 4.50,  unit: "each",      emoji: "🥜" },
  { id: 89, name: "Rice Crackers Plain 100g",           category: "Snacks",          price: 2.20,  unit: "each",      emoji: "🍘" },
  { id: 90, name: "Mixed Nuts Salted 400g",             category: "Snacks",          price: 9.00,  unit: "each",      emoji: "🥜" },
  { id: 91, name: "Shapes Barbecue 175g",               category: "Snacks",          price: 3.50,  unit: "each",      emoji: "🍪" },
  { id: 92, name: "Popcorn Lightly Salted 120g",        category: "Snacks",          price: 3.00,  unit: "each",      emoji: "🍿" },

  // Household (8)
  { id: 93, name: "Toilet Paper 12 Pack 3-Ply",         category: "Household",       price: 9.00,  unit: "each",      emoji: "🧻" },
  { id: 94, name: "Paper Towels 4 Pack",                category: "Household",       price: 6.50,  unit: "each",      emoji: "🧻" },
  { id: 95, name: "Laundry Liquid 2L",                  category: "Household",       price: 12.00, unit: "each",      emoji: "🧺" },
  { id: 96, name: "Dishwashing Liquid 900ml",           category: "Household",       price: 4.50,  unit: "each",      emoji: "🧼" },
  { id: 97, name: "Dishwasher Tablets 40 Pack",         category: "Household",       price: 16.00, unit: "each",      emoji: "🫧" },
  { id: 98, name: "Multipurpose Spray Cleaner 500ml",   category: "Household",       price: 4.00,  unit: "each",      emoji: "🧴" },
  { id: 99, name: "Garbage Bags Large 50 Pack",         category: "Household",       price: 7.50,  unit: "each",      emoji: "🗑️" },
  { id: 100, name: "Sponges Multi Pack 6",              category: "Household",       price: 3.50,  unit: "each",      emoji: "🧽" },
];
